// <auto-generated />
using System;
using Juan_AmparoAP2_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juan_AmparoAP2_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260310000938_Inicial231")]
    partial class Inicial231
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.AsignacionesPuntos", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPuntos")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("EstudianteId");

                    b.ToTable("AsignacionesPuntos");
                });

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.AsignacionesPuntosDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("CantidadPuntos")
                        .HasColumnType("int");

                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoPuntoId")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdAsignacion");

                    b.ToTable("AsignacionesPuntosDetalle");
                });

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<int>("BalancePuntos")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            BalancePuntos = 0,
                            Edad = 20,
                            Email = "ana@yomail.com",
                            Nombres = "Ana Martinez"
                        },
                        new
                        {
                            EstudianteId = 2,
                            BalancePuntos = 0,
                            Edad = 22,
                            Email = "carlos@yopmail.com",
                            Nombres = "Carlos Perez"
                        },
                        new
                        {
                            EstudianteId = 3,
                            BalancePuntos = 0,
                            Edad = 21,
                            Email = "laura@yopmail.com",
                            Nombres = "Laura Rodriguez"
                        });
                });

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.TiposPuntos", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorPuntos")
                        .HasColumnType("int");

                    b.HasKey("TipoId");

                    b.ToTable("TiposPuntos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Activo = true,
                            Color = "primary",
                            Descripcion = "Participacion en clase",
                            Icono = "bi-hand-thumbs-up",
                            Nombre = "Participacion",
                            ValorPuntos = 5
                        },
                        new
                        {
                            TipoId = 2,
                            Activo = true,
                            Color = "success",
                            Descripcion = "Entrega de tarea",
                            Icono = "bi-journal-check",
                            Nombre = "Tarea Entregada",
                            ValorPuntos = 10
                        },
                        new
                        {
                            TipoId = 3,
                            Activo = true,
                            Color = "warning",
                            Descripcion = "Entrega de proyecto",
                            Icono = "bi-lightbulb",
                            Nombre = "Proyecto",
                            ValorPuntos = 20
                        });
                });

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.AsignacionesPuntos", b =>
                {
                    b.HasOne("Juan_AmparoAP2_P2.Models.Estudiantes", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.AsignacionesPuntosDetalle", b =>
                {
                    b.HasOne("Juan_AmparoAP2_P2.Models.AsignacionesPuntos", null)
                        .WithMany("AsignacionesDetalle")
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juan_AmparoAP2_P2.Models.AsignacionesPuntos", b =>
                {
                    b.Navigation("AsignacionesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
